project/finance/urls.py
from django.urls import path

from . import views

app_name = "finance" # Sets the application namespace to "finance"
urlpatterns = [
    path("income/", views.income, name="income"),
    path("addIncome/", views.addIncome, name="addIncome"),
    path("expenses/", views.expenses, name="expenses"),
    path("addExpense", views.addExpense, name="addExpense"),
    path("budgets/", views.budgets, name="budgets"),
    path("addBudget/", views.addBudget, name="addBudget"),
    path("reports/", views.reports, name="reports"),
    path("deleteFinancialObject/", views.deleteFinancialObject, name="deleteFinancialObject"),
    path("generateReport/", views.generateReport, name="generateReport"),
    path("downloadPastReport/<int:report_id>/", views.downloadPastReport, name="downloadPastReport")
]

project/mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic.base import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("dashboard.urls")),
    path("finance/", include("finance.urls")),
    path("authentication/", include("authentication.urls")),
    path("reports/", include("reports.urls")),
    path("admin/", admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/reports/urls.py
from django.urls import path

from . import views

app_name = "reports" # Sets the application namespace to "finance"
urlpatterns = [
    path("createReport/", views.createReport, name="createReport")
]

project/finance/models.py
from django.db import models
import datetime
from django.contrib.auth.models import AbstractUser


# Create your models here.
class User(AbstractUser):
    is_primary_user = models.BooleanField(default=False)

    def __str__(self):
        return self.username
    
class SecondaryUserCode(models.Model):
    primary_user = models.OneToOneField(User, on_delete=models.CASCADE)
    code = models.CharField(max_length=12, unique=True, editable=False)
    
class FinancialObject(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE) # A single user can have many instances of income/expenses/budgets
    value = models.IntegerField(default=0)
    startDate = models.DateField(default=datetime.date.today)
    addDate = models.DateField(default=datetime.date.today)

    class Meta:
        abstract = True # Makes the "FinancialObject" class an Abstract Base Class (ABC)

class Income(FinancialObject):
    source = models.CharField(default="N/A", max_length=200)
    frequency = models.CharField(default="Monthly", max_length=200)
    
class Expense(FinancialObject):
    source = models.CharField(default="N/A", max_length=200)
    category = models.CharField(default="Entertainment", max_length=200)
    frequency = models.CharField(default="Monthly", max_length=200)

class Budget(FinancialObject):
    yearlyValue = models.IntegerField(default=0)
    category = models.CharField(default="Entertainment", max_length=200)
    remainingValueMonth = models.IntegerField(default=0)
    remainingValueYear = models.IntegerField(default=0)

class Report(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    reportType = models.CharField(default="Month", max_length=200)
    file = models.FileField(upload_to="reports/")
    creationDate = models.DateTimeField(auto_now_add=True)


    

project/reports/models.py
from django.db import models

# Create your models here.

project/finance/views.py
from django.shortcuts import render, get_list_or_404, get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse
from datetime import datetime

from django.db.models import Q
from django.template.loader import render_to_string
from weasyprint import HTML
from io import BytesIO
from django.http import FileResponse
from django.core.files.base import ContentFile

from django.contrib.auth.decorators import login_required

from .models import User, Income, Expense, Budget, Report

from .decorators import primary_user_required

# Performs a bubble sort of a given list of financial objects to sort them in ascending order by date of occurrence (startDate).
def sortFinancialObjectsByAscendingDate(list):
    swaps = 1
    while swaps > 0:
        # Loop until no two adjacent objects are swapped (i.e. until all items are in the correct order)
        swaps = 0
        for i in range(len(list)-1):
            if list[i].startDate > list[i+1].startDate:
                # If two adjacent objects are in the wrong order, swap them
                temp = list[i]
                list[i] = list[i+1]
                list[i+1] = temp
                swaps = swaps + 1

    return list

def adjustRelevantBudgetForExpense(expense, type="creation"):
    current_date = datetime.now()
    current_month = current_date.month

    startDate_parsed = datetime.strptime(str(expense.startDate), "%Y-%m-%d")

    if Budget.objects.filter(category=expense.category): 
        # If a budget of this category of expense exists, 
        # subtract/add the value of this expense from/to the values for remaining monthly and yearly spending of the budget
        remainingValueMonth = Budget.objects.get(category=expense.category).remainingValueMonth
        remainingValueYear = Budget.objects.get(category=expense.category).remainingValueYear

        if (startDate_parsed.month == current_month) and (expense.frequency == "One-off"):
            if type == "creation":
                Budget.objects.filter(category=expense.category).update(remainingValueMonth=(remainingValueMonth-int(expense.value)))
            else:
                Budget.objects.filter(category=expense.category).update(remainingValueMonth=(remainingValueMonth+int(expense.value)))

        if expense.frequency == "Monthly":
            # If the frequency of the expense is monthly, then subtract/add 12-times the value of 
            # the expense from/to the remaining value to be spent of the budget for the entire year.
            # Also adjust remaining value to be spent of the budget for the current month
            if type == "creation":
                Budget.objects.filter(category=expense.category).update(remainingValueYear=(remainingValueYear-((12-current_month+1) * int(expense.value))))
                Budget.objects.filter(category=expense.category).update(remainingValueMonth=(remainingValueMonth-int(expense.value)))
            else:
                Budget.objects.filter(category=expense.category).update(remainingValueYear=(remainingValueYear+((12-current_month+1) * int(expense.value))))
                Budget.objects.filter(category=expense.category).update(remainingValueMonth=(remainingValueMonth+int(expense.value)))

        else:
            # Else, subtract/add only the value of the expense
            if type == "creation":
                Budget.objects.filter(category=expense.category).update(remainingValueYear=(remainingValueYear-int(expense.value)))
            else:
                Budget.objects.filter(category=expense.category).update(remainingValueYear=(remainingValueYear+int(expense.value)))

@login_required
def income(request):
    message = request.GET.get("message", "")
    # Sorting income in ascending order of date added
    income = sortFinancialObjectsByAscendingDate(list(Income.objects.all()))
    return render(
        request, 
        "finance/income.html", 
        {
            "income": income,
            "message": message
        }
    )

@login_required
@primary_user_required
def addIncome(request):
    try:
        input_value = int(request.POST["value"])
        input_source = request.POST["source"]
        input_frequency = request.POST["frequency"]
        input_startDate = request.POST["startDate"]
    except:
        income = Income.objects.all()
        return render(
            request, 
            "finance/income.html", 
            {
                "income": income,
                "message": "All fields must be complete."
            }
        )
    else:
        # Create the income object and save it to the database
        income = Income(user=User.objects.get(is_primary_user=True), 
                        value=input_value, 
                        source=input_source, 
                        frequency=input_frequency, 
                        startDate=input_startDate)
        income.save()
            
        return HttpResponseRedirect(f"{reverse('finance:income')}?message=Income added successfully.")

@login_required
def expenses(request):
    message = request.GET.get("message", "")
    # Sorting expenses in ascending order of date added
    expenses = sortFinancialObjectsByAscendingDate(list(Expense.objects.all()))
    return render(
        request, 
        "finance/expenses.html", 
        {
            "expenses": expenses,
            "message": message
        }
    )

@login_required
@primary_user_required
def addExpense(request):
    try:
        input_category = request.POST["category"]
        input_value = int(request.POST["value"])
        input_source = request.POST["source"]
        input_frequency = request.POST["frequency"]
        input_startDate = request.POST["startDate"]
    except:
        expenses = Expense.objects.all()
        return render(
            request, 
            "finance/expenses.html", 
            {
                "expenses": expenses,
                "message": "All fields must be complete."
            }
        )
    else:
        # Create the expense object and save it to the database
        expense = Expense(user=User.objects.get(is_primary_user=True), 
                          category=input_category, 
                          value=input_value, 
                          frequency=input_frequency, 
                          source=input_source, 
                          startDate=input_startDate)
        expense.save()

        adjustRelevantBudgetForExpense(expense, "creation")
            
        return HttpResponseRedirect(f"{reverse('finance:expenses')}?message=Expense added successfully.")

@login_required
def budgets(request):
    message = request.GET.get("message", "")
    # Sorting budgets in ascending order of date added
    budgets = sortFinancialObjectsByAscendingDate(list(Budget.objects.all()))
    return render(
        request, 
        "finance/budgets.html", 
        {
            "budgets": budgets,
            "message": message
        }
    )

@login_required
@primary_user_required
def addBudget(request):
    try:
        input_category = request.POST["category"]
        input_value = int(request.POST["value"]) # Convert input string to integer to avoid errors during multiplication below
        input_startDate = request.POST["startDate"]
    except:
        budgets = Budget.objects.all()
        return render(
            request, 
            "finance/budgets.html", 
            {
                "budgets": budgets,
                "message": "All fields must be complete."
            }
        )
    else:
        current_date = datetime.now()
        current_year = current_date.year
        current_month = current_date.month

        deletedBudget = False
        
        if Budget.objects.filter(category=input_category):
            # If a budget of this category already exists, delete the one that already exists, 
            # as a user cannot have more than one budget for a category
            Budget.objects.filter(category=input_category).delete()
            deletedBudget = True

        yearlyValue = 12 * input_value # yearlyValue is 12-times the monthly (input) value
        
        # Create the budget object and save it to the database
        budget = Budget(user=User.objects.get(is_primary_user=True), 
                        category=input_category, 
                        value=input_value, 
                        remainingValueMonth=input_value, 
                        startDate=input_startDate, 
                        yearlyValue=yearlyValue, 
                        remainingValueYear=yearlyValue)
        budget.save()

        if Expense.objects.filter(category=input_category):
            # If expenses for this category already exist, 
            # create a list of them
            requiredExpenses = get_list_or_404(Expense.objects.filter(category=input_category))
                    
            for i in range(len(requiredExpenses)):
                # Iterate through the list of expenses and subtract their respective values from 
                # the values for remaining monthly and yearly spending of this budget
                

                expenseValue = requiredExpenses[i].value
                remainingValueMonth = Budget.objects.get(category=input_category).remainingValueMonth
                remainingValueYear = Budget.objects.get(category=input_category).remainingValueYear

                if (requiredExpenses[i].startDate.month == current_month) and (requiredExpenses[i].frequency == "One-off"):
                    remainingValueMonth -= expenseValue

                if requiredExpenses[i].frequency == "Monthly":
                    # If an expense has a monthly frequency, then subtract 12-times the value of the expense from the
                    # remaining value to be spent for the budget for this year.
                    # Also adjust remaining value to be spent of the budget for the current month

project/reports/views.py
from django.shortcuts import render

# Create your views here.
def createReport(request):
    pass

project/finance/templates/finance/budgets.html
{% extends "finance/finance-base.html" %}

{% load finance_extras %}

{% block title %}Budgets{% endblock %}

{% block header-title %}Budgets{% endblock %}

{% block finance_extra_css %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'finance/budgets-style.css' %}">
{% endblock %}

{% block saved-label %}Saved budgets:{% endblock %}

{% block presence-check-and-list %}
    {% if budgets %}
        {% for i in budgets %}
            <li class="card">
                <div class="card-icon">
                    <svg width="20px" height="20px" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M6 11V15M18 9V13M17 4C19.4487 4 20.7731 4.37476 21.4321 4.66544C21.5199 4.70415 21.5638 4.72351 21.6904 4.84437C21.7663 4.91682 21.9049 5.12939 21.9405 5.22809C22 5.39274 22 5.48274 22 5.66274V16.4111C22 17.3199 22 17.7743 21.8637 18.0079C21.7251 18.2454 21.5914 18.3559 21.3319 18.4472C21.0769 18.5369 20.562 18.438 19.5322 18.2401C18.8114 18.1017 17.9565 18 17 18C14 18 11 20 7 20C4.55129 20 3.22687 19.6252 2.56788 19.3346C2.48012 19.2958 2.43624 19.2765 2.3096 19.1556C2.23369 19.0832 2.09512 18.8706 2.05947 18.7719C2 18.6073 2 18.5173 2 18.3373L2 7.58885C2 6.68009 2 6.2257 2.13628 5.99214C2.2749 5.75456 2.40859 5.64412 2.66806 5.55281C2.92314 5.46305 3.43803 5.56198 4.46783 5.75985C5.18862 5.89834 6.04348 6 7 6C10 6 13 4 17 4ZM14.5 12C14.5 13.3807 13.3807 14.5 12 14.5C10.6193 14.5 9.5 13.3807 9.5 12C9.5 10.6193 10.6193 9.5 12 9.5C13.3807 9.5 14.5 10.6193 14.5 12Z" stroke="white" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/></svg>
                </div>
                <div class="card-info">
                    <div><strong>Category</strong></div><div>{{ i.category }}</div>
                    <div><strong>Maximum spending for 1 month</strong></div><div>£{{ i.value }}</div> 
                    <div><strong>Maximum spending for 1 year</strong></div><div>£{{ i.yearlyValue }}</div>

                    <div><strong>Remaining spending for the month</strong></div>
                    {% if i.remainingValueMonth >= 0 %} 
                        <div>£{{ i.remainingValueMonth }}</div>
                    {% else %}
                        <div><strong>Warning</strong> - over-budget by £{{ i.remainingValueMonth|absoluteValue }}</div>
                    {% endif %}
                    
                    <div><strong>Remaining spending for the year</strong></div>
                    {% if i.remainingValueYear >= 0 %}
                        <div>£{{ i.remainingValueYear }}</div>
                    {% else %}
                        <div><strong>Warning</strong> - over-budget by £{{ i.remainingValueYear|absoluteValue }}</div>
                    {% endif %}

                    <div><strong>Start date</strong></div><div>{{ i.startDate }}</div>
                    <div><strong>Date added</strong></div><div>{{ i.addDate }}</div>                           
                </div>
                <form action="{% url 'finance:deleteFinancialObject' %}" method="post" class="form" style="width:0;height:0;">
                    {% csrf_token %}
                    <input type="hidden" name="object_id" value="{{ i.id }}">
                    <input type="hidden" name="finance_type" value="budgets">
                    <input type="hidden" name="financial_object" value="{{ i }}">
                    <div class="delete-button">
                        <input type="submit" value="Delete">
                    </div>
                </form>
            </li>
        {% endfor %}
    {% else %}
        <li>No budgets added yet.</li>
    {% endif %}
{% endblock %}

{% block enter-label %}Enter new budget:{% endblock %}

{% block form %}
    {% if user.is_primary_user %}
        <form action="{% url 'finance:addBudget' %}" method="post" class="form">
            {% csrf_token %}
            <div class="form-components">
                <div class="form-labels-and-answers">
                    <div class="form-labels">
                        <label for="value"><strong>Maximum spending for 1 month</strong>    £</label>

                        <label for="category"><strong>Category</strong></label>

                        <label for="startDate"><strong>Start date</strong></label>
                    </div>
                    <div class="form-answers">
                        <input type="text" id="value" name="value">
                        
                        <select id="category" name="category">
                            <option value="Entertainment">Entertainment</option>
                            <option value="Eating out">Eating out</option>
                            <option value="Groceries">Groceries</option>
                            <option value="Travel">Travel</option>
                            <option value="Education">Education</option>
                            <option value="Clothing">Clothing</option>
                            <option value="Insurance">Insurance</option>
                            <option value="Healthcare">Healthcare</option>
                            <option value="Housing">Housing</option>
                            <option value="Debt">Debt</option>
                            <option value="Gifts">Gifts</option>
                        </select>

                        <input type="date" id="startDate" name="startDate" value=date>
                    </div>
                </div>

                <div class="submit">
                    <input type="submit" value="Add budget">
                </div>
            </div>

        </form>
    {% else %}
            <p>Only primary users can perform this action.</p>
    {% endif %}
{% endblock %}

project/finance/templates/finance/expenses.html
{% extends "finance/finance-base.html" %}

{% block title %}Expenses{% endblock %}

{% block header-title %}Expenses{% endblock %}

{% block finance_extra_css %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'finance/expenses-style.css' %}">
{% endblock %}

{% block saved-label %}Saved expenses:{% endblock %}

{% block presence-check-and-list %}
    {% if expenses %}
        {% for i in expenses %}
            <li class="card">
                <div class="card-icon">
                    <svg width="20px" height="20px" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M6 11V15M18 9V13M17 4C19.4487 4 20.7731 4.37476 21.4321 4.66544C21.5199 4.70415 21.5638 4.72351 21.6904 4.84437C21.7663 4.91682 21.9049 5.12939 21.9405 5.22809C22 5.39274 22 5.48274 22 5.66274V16.4111C22 17.3199 22 17.7743 21.8637 18.0079C21.7251 18.2454 21.5914 18.3559 21.3319 18.4472C21.0769 18.5369 20.562 18.438 19.5322 18.2401C18.8114 18.1017 17.9565 18 17 18C14 18 11 20 7 20C4.55129 20 3.22687 19.6252 2.56788 19.3346C2.48012 19.2958 2.43624 19.2765 2.3096 19.1556C2.23369 19.0832 2.09512 18.8706 2.05947 18.7719C2 18.6073 2 18.5173 2 18.3373L2 7.58885C2 6.68009 2 6.2257 2.13628 5.99214C2.2749 5.75456 2.40859 5.64412 2.66806 5.55281C2.92314 5.46305 3.43803 5.56198 4.46783 5.75985C5.18862 5.89834 6.04348 6 7 6C10 6 13 4 17 4ZM14.5 12C14.5 13.3807 13.3807 14.5 12 14.5C10.6193 14.5 9.5 13.3807 9.5 12C9.5 10.6193 10.6193 9.5 12 9.5C13.3807 9.5 14.5 10.6193 14.5 12Z" stroke="white" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/></svg>
                </div>
                <div class="card-info">
                    <div><strong>Value</strong></div><div>£{{ i.value }}</div> 
                    <div><strong>Category</strong></div><div>{{ i.category }}</div> 
                    <div><strong>Source</strong></div><div>{{ i.source }}</div>
                    <div><strong>Frequency</strong></div><div>{{ i.frequency }}</div>
                    <div><strong>Start date</strong></div><div>{{ i.startDate }}</div>
                    <div><strong>Date added</strong></div><div>{{ i.addDate }}</div>                           
                </div>
                <form action="{% url 'finance:deleteFinancialObject' %}" method="post" class="form" style="width:0;height:0;">
                    {% csrf_token %}
                    <input type="hidden" name="object_id" value="{{ i.id }}">
                    <input type="hidden" name="finance_type" value="expenses">
                    <input type="hidden" name="financial_object" value="{{ i }}">
                    <div class="delete-button">
                        <input type="submit" value="Delete">
                    </div>
                </form>
            </li>
        {% endfor %}
    {% else %}
        <li>No expenses added yet.</li>
    {% endif %}
{% endblock %}

{% block enter-label %}Enter new expense:{% endblock %}

{% block form %}
    {% if request.user.is_primary_user %}
        <form action="{% url 'finance:addExpense' %}" method="post" class="form">
            {% csrf_token %}
            <div class="form-components">
                <div class="form-labels-and-answers">
                    <div class="form-labels">
                        <label for="value"><strong>Value</strong>    £</label>

                        <label for="source"><strong>Source</strong></label>

                        <label for="category"><strong>Category</strong></label>

                        <div><strong>Frequency</strong></div>

                        <label for="startDate"><strong>Start date</strong></label>
                    </div>
                    <div class="form-answers">
                        <input type="text" id="value" name="value">

                        <input type="text" id="source" name="source">
                        
                        <select id="category" name="category">
                            <option value="Entertainment">Entertainment</option>
                            <option value="Eating out">Eating out</option>
                            <option value="Groceries">Groceries</option>
                            <option value="Travel">Travel</option>
                            <option value="Education">Education</option>
                            <option value="Clothing">Clothing</option>
                            <option value="Insurance">Insurance</option>
                            <option value="Healthcare">Healthcare</option>
                            <option value="Housing">Housing</option>
                            <option value="Debt">Debt</option>
                            <option value="Gifts">Gifts</option>
                        </select>

                        <select id="frequency" name="frequency">
                            <option value="One-off">One-off</option>
                            <option value="Monthly">Monthly</option>
                            <option value="Yearly">Yearly</option>
                        </select> 

                        <input type="date" id="startDate" name="startDate" value=date>
                    </div>
                </div>

                <div class="submit">
                    <input type="submit" value="Add expense">
                </div>
            </div>

        </form>
    {% else %}
            <p>Only primary users can perform this action.</p>
    {% endif %}
{% endblock %}

project/finance/templates/finance/income.html
{% extends "finance/finance-base.html" %}

{% block title %}Income{% endblock %}

{% block header-title %}Income{% endblock %}

{% block finance_extra_css %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'finance/income-style.css' %}">
{% endblock %}

{% block saved-label %}Saved income:{% endblock %}

{% block presence-check-and-list %}
    {% if income %}
        {% for i in income %}
            <li class="card">
                <div class="card-icon">
                    <svg width="20px" height="20px" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M13.5295 8.35186C12.9571 8.75995 12.2566 9 11.5 9C9.567 9 8 7.433 8 5.5C8 3.567 9.567 2 11.5 2C12.753 2 13.8522 2.65842 14.4705 3.64814M6 20.0872H8.61029C8.95063 20.0872 9.28888 20.1277 9.61881 20.2086L12.3769 20.8789C12.9753 21.0247 13.5988 21.0388 14.2035 20.9214L17.253 20.3281C18.0585 20.1712 18.7996 19.7854 19.3803 19.2205L21.5379 17.1217C22.154 16.5234 22.154 15.5524 21.5379 14.9531C20.9832 14.4134 20.1047 14.3527 19.4771 14.8103L16.9626 16.6449C16.6025 16.9081 16.1643 17.0498 15.7137 17.0498H13.2855L14.8311 17.0498C15.7022 17.0498 16.4079 16.3633 16.4079 15.5159V15.2091C16.4079 14.5055 15.9156 13.892 15.2141 13.7219L12.8286 13.1417C12.4404 13.0476 12.0428 13 11.6431 13C10.6783 13 8.93189 13.7988 8.93189 13.7988L6 15.0249M20 6.5C20 8.433 18.433 10 16.5 10C14.567 10 13 8.433 13 6.5C13 4.567 14.567 3 16.5 3C18.433 3 20 4.567 20 6.5ZM2 14.6L2 20.4C2 20.9601 2 21.2401 2.10899 21.454C2.20487 21.6422 2.35785 21.7951 2.54601 21.891C2.75992 22 3.03995 22 3.6 22H4.4C4.96005 22 5.24008 22 5.45399 21.891C5.64215 21.7951 5.79513 21.6422 5.89101 21.454C6 21.2401 6 20.9601 6 20.4V14.6C6 14.0399 6 13.7599 5.89101 13.546C5.79513 13.3578 5.64215 13.2049 5.45399 13.109C5.24008 13 4.96005 13 4.4 13L3.6 13C3.03995 13 2.75992 13 2.54601 13.109C2.35785 13.2049 2.20487 13.3578 2.10899 13.546C2 13.7599 2 14.0399 2 14.6Z" stroke="white" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/></svg>
                </div>
                <div class="card-info">
                    <div><strong>Value</strong></div><div>£{{ i.value }}</div>  
                    <div><strong>Source</strong></div><div>{{ i.source }}</div>
                    <div><strong>Frequency</strong></div><div>{{ i.frequency }}</div>
                    <div><strong>Start date</strong></div><div>{{ i.startDate }}</div>
                    <div><strong>Date added</strong></div><div>{{ i.addDate }}</div>                           
                </div>
                <form action="{% url 'finance:deleteFinancialObject' %}" method="post" class="form" style="width:0;height:0;">
                    {% csrf_token %}
                    <input type="hidden" name="object_id" value="{{ i.id }}">
                    <input type="hidden" name="finance_type" value="income">
                    <input type="hidden" name="financial_object" value="{{ i }}">
                    <div class="delete-button">
                        <input type="submit" value="Delete">
                    </div>
                </form>
            </li>
        {% endfor %}
    {% else %}
        <li>No income added yet.</li>
    {% endif %}
{% endblock %}

{% block enter-label %}Enter new income:{% endblock %}

{% block form %}
    {% if request.user.is_primary_user %}
        <form action="{% url 'finance:addIncome' %}" method="post" class="form">
            {% csrf_token %}
            <div class="form-components">
                <div class="form-labels-and-answers">
                    <div class="form-labels">
                        <label for="value"><strong>Value</strong>    £</label>

                        <label for="source"><strong>Source</strong></label>

                        <div><strong>Frequency</strong></div>

                        <label for="startDate"><strong>Start date</strong></label>
                    </div>
                    <div class="form-answers">
                        <input type="text" id="value" name="value">

                        <input type="text" id="source" name="source">
                        
                        <select id="frequency" name="frequency">
                            <option value="One-off">One-off</option>
                            <option value="Monthly">Monthly</option>
                            <option value="Yearly">Yearly</option>
                        </select> 

                        <input type="date" id="startDate" name="startDate" value=date>
                    </div>
                </div>

                <div class="submit">
                    <input type="submit" value="Add income">
                </div>
            </div>

        </form>
    {% else %}
        <p>Only primary users can perform this action.</p>
    {% endif %}
{% endblock %}

project/finance/templates/finance/reports.html
{% extends "finance/finance-base.html" %}

{% block title %}Reports{% endblock %}

{% block header-title %}Reports{% endblock %}

{% block finance_extra_css %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'finance/reports-style.css' %}">
{% endblock %}

{% block saved-label %}Past reports:{% endblock %}

{% block presence-check-and-list %}
    {% if reports %}
        {% for i in reports %}
            <li id="past-report">
               <a href="{% url 'finance:downloadPastReport' i.id %}">Report on {{ i.creationDate }} (Type: {{ i.reportType }})</a> 
            </li>
        {% endfor %}
    {% else %}
        <li>No reports generated yet.</li>
    {% endif %}
{% endblock %}

{% block enter-label %}Generate report:{% endblock %}
{% block form %}
    <form action="{% url 'finance:generateReport' %}" method="post" class="form">
        {% csrf_token %}
        <div class="form-components">
            <div class="form-labels-and-answers">
                <div class="form-labels">
                    <div><strong>Type</strong></div>
                </div>
                <div class="form-answers">
                    <select id="type" name="type">
                        <option value="Month">Current month</option>
                        <option value="Year">Current year</option>
                    </select> 
                </div>
            </div>

            <div class="submit">
                <input type="submit" value="Generate report">
            </div>
        </div>

    </form>
{% endblock %}