project/authentication/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

app_name = "authentication" # Sets the application namespace to "authentication"
urlpatterns = [
    path("login/", auth_views.LoginView.as_view(), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("register/", views.register, name="register")
]

project/dashboard/urls.py
from django.urls import path

from . import views

app_name = "dashboard" # Sets the application namespace to "finance"
urlpatterns = [
    path("dashboard/", views.dashboard, name="dashboard")
]

project/finance/urls.py
from django.urls import path

from . import views

app_name = "finance" # Sets the application namespace to "finance"
urlpatterns = [
    path("income/", views.income, name="income"),
    path("addIncome/", views.addIncome, name="addIncome"),
    path("expenses/", views.expenses, name="expenses"),
    path("addExpense", views.addExpense, name="addExpense"),
    path("budgets/", views.budgets, name="budgets"),
    path("addBudget/", views.addBudget, name="addBudget"),
    path("reports/", views.reports, name="reports"),
    path("deleteFinancialObject/", views.deleteFinancialObject, name="deleteFinancialObject"),
    path("generateReport/", views.generateReport, name="generateReport"),
    path("downloadPastReport/<int:report_id>/", views.downloadPastReport, name="downloadPastReport")
]

project/mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic.base import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("dashboard.urls")),
    path("finance/", include("finance.urls")),
    path("authentication/", include("authentication.urls")),
    path("reports/", include("reports.urls")),
    path("admin/", admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/dashboard/models.py
from django.db import models

# Create your models here.

project/dashboard/views.py
from django.shortcuts import render
from finance.models import User, Income, Expense, SecondaryUserCode
from django.db.models import Q
from datetime import datetime
from django.contrib.auth.decorators import login_required


# Create your views here.
@login_required
def dashboard(request):
    # Avoid repetition of summation of FinancialObjects below (4 times) through the use of the following function
    def sumFinancialObjectsFromList(l, timeframe="Month"):
        sum = 0
        for i in range(len(l)):
            if l[i].frequency == "Monthly" and timeframe == "Year":
                # If the FinancialObject has a monthly frequency, and the specified timeframe for the summation is a year,
                # then multiply the value of the FinancialObject by 12 to account for this
                value_to_add = (12-l[i].startDate.month+1) * l[i].value
            else:
                # Else, simply add the value of the FinancialObject
                value_to_add = l[i].value
            
            sum += value_to_add

        return sum
    
    user = request.user

    current_date = datetime.now()
    current_year = current_date.year
    current_month = current_date.month
    
    # Create lists of relevant Income objects for the current month/year by filtering with Q()
    current_month_income = list(Income.objects.filter(Q(frequency="Monthly") | (Q(frequency="One-off") & Q(startDate__month=str(current_month))) | (Q(frequency="Yearly") & Q(startDate__month=str(current_month)))))
    current_year_income = list(Income.objects.filter(Q(frequency="Monthly") | (Q(frequency="One-off") & Q(startDate__year=str(current_year))) | Q(frequency="Yearly")))

    # Create lists of relevant Expense objects for the current month/year by filtering with Q()
    current_month_expenses = list(Expense.objects.filter(Q(frequency="Monthly") | (Q(frequency="One-off") & Q(startDate__month=str(current_month))) | (Q(frequency="Yearly") & Q(startDate__month=str(current_month)))))
    current_year_expenses = list(Expense.objects.filter(Q(frequency="Monthly") | (Q(frequency="One-off") & Q(startDate__year=str(current_year))) | Q(frequency="Yearly")))


    # Sum all income for the current month/year
    current_month_income_total = sumFinancialObjectsFromList(current_month_income)
    current_year_income_total = sumFinancialObjectsFromList(current_year_income, "Year")

    # Sum all expenses for the current month/year
    current_month_expenses_total = sumFinancialObjectsFromList(current_month_expenses)
    current_year_expenses_total = sumFinancialObjectsFromList(current_year_expenses, "Year")

    # Calculate net income for both the current month and the current year
    current_month_net_income = current_month_income_total - current_month_expenses_total
    current_year_net_income = current_year_income_total - current_year_expenses_total

    # Change current_month to its equivalent English-language string for use in displaying in index.html
    if current_month == 1:
        current_month = "January"
    elif current_month == 2:
        current_month = "February"
    elif current_month == 3:
        current_month = "March"
    elif current_month == 4:
        current_month = "April"
    elif current_month == 5:
        current_month = "May"
    elif current_month == 6:
        current_month = "June"
    elif current_month == 7:
        current_month = "July"
    elif current_month == 8:
        current_month = "August"
    elif current_month == 9:
        current_month = "September"
    elif current_month == 10:
        current_month = "October"
    elif current_month == 11:
        current_month = "November"
    else:
        current_month = "December"

    users = list(User.objects.filter(is_superuser=False))
    if len(users) > 0:
        inviteCode = SecondaryUserCode.objects.get()
    else:
        inviteCode = None

    return render(
        request, 
        "dashboard/dashboard.html", 
        {
            "user": user,
            "inviteCode": inviteCode,
            "current_month": current_month,
            "current_year": current_year,
            "current_month_income_total": current_month_income_total,
            "current_year_income_total": current_year_income_total,
            "current_month_expenses_total": current_month_expenses_total,
            "current_year_expenses_total": current_year_expenses_total,
            "current_month_net_income": current_month_net_income,
            "current_year_net_income": current_year_net_income
        }
    )

project/dashboard/templates/dashboard/base.html
<!-- All web pages inherit from this one in order to avoid repeating the HTML and CSS for the 
 header and sidebar (and the CSS for the general style of the whole website),
 which will be the same across all web pages -->

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Finance App{% endblock %}</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'dashboard/base-style.css' %}">
    {% block extra_css %}{% endblock %}
    <script src="{% static 'dashboard/base-script.js' %}"></script>
    {% block extra_js %}{% endblock %}
</head>
<body>
    <div class="header">
        <ul class="header-left-side">
            <li>
                <button id="open-sidebar">
                    <svg width="20" height="20" viewBox="0 0 20 20" fill="none">
                        <rect y="3" width="20" height="2" fill="#fff"/>
                        <rect y="9" width="20" height="2" fill="#fff"/>
                        <rect y="15" width="20" height="2" fill="#fff"/>
                    </svg>
                </button>
                <div id="sidebar" class="sidebar">
                    <ul class="sidebar-list">
                        <li><a href="javascript:void(0)" id="close-sidebar">&times;</a></li>
                        <li><a href="{% url 'dashboard:dashboard' %}">
                            <svg width="20px" height="20px" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M12.9823 2.764C12.631 2.49075 12.4553 2.35412 12.2613 2.3016C12.0902 2.25526 11.9098 2.25526 11.7387 2.3016C11.5447 2.35412 11.369 2.49075 11.0177 2.764L4.23539 8.03912C3.78202 8.39175 3.55534 8.56806 3.39203 8.78886C3.24737 8.98444 3.1396 9.20478 3.07403 9.43905C3 9.70352 3 9.9907 3 10.5651V17.8C3 18.9201 3 19.4801 3.21799 19.908C3.40973 20.2843 3.71569 20.5903 4.09202 20.782C4.51984 21 5.0799 21 6.2 21H8.2C8.48003 21 8.62004 21 8.727 20.9455C8.82108 20.8976 8.89757 20.8211 8.9455 20.727C9 20.62 9 20.48 9 20.2V13.6C9 13.0399 9 12.7599 9.10899 12.546C9.20487 12.3578 9.35785 12.2049 9.54601 12.109C9.75992 12 10.0399 12 10.6 12H13.4C13.9601 12 14.2401 12 14.454 12.109C14.6422 12.2049 14.7951 12.3578 14.891 12.546C15 12.7599 15 13.0399 15 13.6V20.2C15 20.48 15 20.62 15.0545 20.727C15.1024 20.8211 15.1789 20.8976 15.273 20.9455C15.38 21 15.52 21 15.8 21H17.8C18.9201 21 19.4802 21 19.908 20.782C20.2843 20.5903 20.5903 20.2843 20.782 19.908C21 19.4801 21 18.9201 21 17.8V10.5651C21 9.9907 21 9.70352 20.926 9.43905C20.8604 9.20478 20.7526 8.98444 20.608 8.78886C20.4447 8.56806 20.218 8.39175 19.7646 8.03913L12.9823 2.764Z" stroke="white" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/></svg>
                            <div>Dashboard</div>
                        </a></li>
                        <li><a href="{% url 'finance:income' %}">
                            <svg width="20px" height="20px" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M13.5295 8.35186C12.9571 8.75995 12.2566 9 11.5 9C9.567 9 8 7.433 8 5.5C8 3.567 9.567 2 11.5 2C12.753 2 13.8522 2.65842 14.4705 3.64814M6 20.0872H8.61029C8.95063 20.0872 9.28888 20.1277 9.61881 20.2086L12.3769 20.8789C12.9753 21.0247 13.5988 21.0388 14.2035 20.9214L17.253 20.3281C18.0585 20.1712 18.7996 19.7854 19.3803 19.2205L21.5379 17.1217C22.154 16.5234 22.154 15.5524 21.5379 14.9531C20.9832 14.4134 20.1047 14.3527 19.4771 14.8103L16.9626 16.6449C16.6025 16.9081 16.1643 17.0498 15.7137 17.0498H13.2855L14.8311 17.0498C15.7022 17.0498 16.4079 16.3633 16.4079 15.5159V15.2091C16.4079 14.5055 15.9156 13.892 15.2141 13.7219L12.8286 13.1417C12.4404 13.0476 12.0428 13 11.6431 13C10.6783 13 8.93189 13.7988 8.93189 13.7988L6 15.0249M20 6.5C20 8.433 18.433 10 16.5 10C14.567 10 13 8.433 13 6.5C13 4.567 14.567 3 16.5 3C18.433 3 20 4.567 20 6.5ZM2 14.6L2 20.4C2 20.9601 2 21.2401 2.10899 21.454C2.20487 21.6422 2.35785 21.7951 2.54601 21.891C2.75992 22 3.03995 22 3.6 22H4.4C4.96005 22 5.24008 22 5.45399 21.891C5.64215 21.7951 5.79513 21.6422 5.89101 21.454C6 21.2401 6 20.9601 6 20.4V14.6C6 14.0399 6 13.7599 5.89101 13.546C5.79513 13.3578 5.64215 13.2049 5.45399 13.109C5.24008 13 4.96005 13 4.4 13L3.6 13C3.03995 13 2.75992 13 2.54601 13.109C2.35785 13.2049 2.20487 13.3578 2.10899 13.546C2 13.7599 2 14.0399 2 14.6Z" stroke="white" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/></svg>
                            <div>Income</div>
                        </a></li>
                        <li><a href="{% url 'finance:expenses' %}">
                            <svg width="20px" height="20px" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M6 11V15M18 9V13M17 4C19.4487 4 20.7731 4.37476 21.4321 4.66544C21.5199 4.70415 21.5638 4.72351 21.6904 4.84437C21.7663 4.91682 21.9049 5.12939 21.9405 5.22809C22 5.39274 22 5.48274 22 5.66274V16.4111C22 17.3199 22 17.7743 21.8637 18.0079C21.7251 18.2454 21.5914 18.3559 21.3319 18.4472C21.0769 18.5369 20.562 18.438 19.5322 18.2401C18.8114 18.1017 17.9565 18 17 18C14 18 11 20 7 20C4.55129 20 3.22687 19.6252 2.56788 19.3346C2.48012 19.2958 2.43624 19.2765 2.3096 19.1556C2.23369 19.0832 2.09512 18.8706 2.05947 18.7719C2 18.6073 2 18.5173 2 18.3373L2 7.58885C2 6.68009 2 6.2257 2.13628 5.99214C2.2749 5.75456 2.40859 5.64412 2.66806 5.55281C2.92314 5.46305 3.43803 5.56198 4.46783 5.75985C5.18862 5.89834 6.04348 6 7 6C10 6 13 4 17 4ZM14.5 12C14.5 13.3807 13.3807 14.5 12 14.5C10.6193 14.5 9.5 13.3807 9.5 12C9.5 10.6193 10.6193 9.5 12 9.5C13.3807 9.5 14.5 10.6193 14.5 12Z" stroke="white" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/></svg>
                            <div>Expenses</div>
                        </a></li>
                        <li><a href="{% url 'finance:budgets' %}">
                            <svg width="20px" height="20px" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M2 17V16.8498C2 16.5333 2 16.3751 2.02421 16.2209C2.0457 16.084 2.08136 15.9497 2.13061 15.8202C2.18609 15.6743 2.2646 15.5369 2.42162 15.2622L6 9M2 17C2 19.2091 3.79086 21 6 21C8.20914 21 10 19.2091 10 17M2 17V16.8C2 16.52 2 16.38 2.0545 16.273C2.10243 16.1789 2.17892 16.1024 2.273 16.0545C2.37996 16 2.51997 16 2.8 16H9.2C9.48003 16 9.62004 16 9.727 16.0545C9.82108 16.1024 9.89757 16.1789 9.9455 16.273C10 16.38 10 16.52 10 16.8V17M6 9L9.57838 15.2622C9.7354 15.5369 9.81391 15.6743 9.86939 15.8202C9.91864 15.9497 9.9543 16.084 9.97579 16.2209C10 16.3751 10 16.5333 10 16.8498V17M6 9L18 7M14 15V14.8498C14 14.5333 14 14.3751 14.0242 14.2209C14.0457 14.084 14.0814 13.9497 14.1306 13.8202C14.1861 13.6743 14.2646 13.5369 14.4216 13.2622L18 7M14 15C14 17.2091 15.7909 19 18 19C20.2091 19 22 17.2091 22 15M14 15V14.8C14 14.52 14 14.38 14.0545 14.273C14.1024 14.1789 14.1789 14.1024 14.273 14.0545C14.38 14 14.52 14 14.8 14H21.2C21.48 14 21.62 14 21.727 14.0545C21.8211 14.1024 21.8976 14.1789 21.9455 14.273C22 14.38 22 14.52 22 14.8V15M18 7L21.5784 13.2622C21.7354 13.5369 21.8139 13.6743 21.8694 13.8202C21.9186 13.9497 21.9543 14.084 21.9758 14.2209C22 14.3751 22 14.5333 22 14.8498V15M12 3V8" stroke="white" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/></svg>
                            <div>Budgets</div>
                        </a></li>
                    </ul>
                </div>
            </li>
            {% load static %}
            <a href="{% url 'dashboard:dashboard' %}" class="logo-link">
                <img src="{% static 'dashboard/logo.png' %}">
            </a>
            <li>{% block header-title %}Dashboard{% endblock %}</li>
        </ul>
        <ul class="header-right-side">
            <li>
                [User]
            </li>
            <li>
                <button class="header-log-out">Log out</button>
            </li>
        </ul>
    </div>
    {% block content %}{% endblock %}
</body>
</html>

project/dashboard/templates/dashboard/navbar-and-sidebar-base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <!-- Title can be changed depending on the webpage -->
    <title>{% block title %}Finance App{% endblock %}</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'dashboard/navbar-and-sidebar-base-style.css' %}">
    <!-- Extra CSS and JS can be added if required for the webpage -->
    {% block extra_css %}{% endblock %}
    <script src="{% static 'dashboard/navbar-and-sidebar-base-script.js' %}"></script>
    {% block extra_js %}{% endblock %}
</head>
<body>
    <div class="header">
        <ul class="header-left-side">
            <li>
                <button id="open-sidebar">
                    <svg width="20" height="20" viewBox="0 0 20 20" fill="none">
                        <rect y="3" width="20" height="2" fill="#fff"/>
                        <rect y="9" width="20" height="2" fill="#fff"/>
                        <rect y="15" width="20" height="2" fill="#fff"/>
                    </svg>
                </button>
                <div id="sidebar" class="sidebar">
                    <ul class="sidebar-list">
                        <li><a href="javascript:void(0)" id="close-sidebar">&times;</a></li>
                        <li><a href="{% url 'dashboard:dashboard' %}">
                            <svg width="20px" height="20px" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M12.9823 2.764C12.631 2.49075 12.4553 2.35412 12.2613 2.3016C12.0902 2.25526 11.9098 2.25526 11.7387 2.3016C11.5447 2.35412 11.369 2.49075 11.0177 2.764L4.23539 8.03912C3.78202 8.39175 3.55534 8.56806 3.39203 8.78886C3.24737 8.98444 3.1396 9.20478 3.07403 9.43905C3 9.70352 3 9.9907 3 10.5651V17.8C3 18.9201 3 19.4801 3.21799 19.908C3.40973 20.2843 3.71569 20.5903 4.09202 20.782C4.51984 21 5.0799 21 6.2 21H8.2C8.48003 21 8.62004 21 8.727 20.9455C8.82108 20.8976 8.89757 20.8211 8.9455 20.727C9 20.62 9 20.48 9 20.2V13.6C9 13.0399 9 12.7599 9.10899 12.546C9.20487 12.3578 9.35785 12.2049 9.54601 12.109C9.75992 12 10.0399 12 10.6 12H13.4C13.9601 12 14.2401 12 14.454 12.109C14.6422 12.2049 14.7951 12.3578 14.891 12.546C15 12.7599 15 13.0399 15 13.6V20.2C15 20.48 15 20.62 15.0545 20.727C15.1024 20.8211 15.1789 20.8976 15.273 20.9455C15.38 21 15.52 21 15.8 21H17.8C18.9201 21 19.4802 21 19.908 20.782C20.2843 20.5903 20.5903 20.2843 20.782 19.908C21 19.4801 21 18.9201 21 17.8V10.5651C21 9.9907 21 9.70352 20.926 9.43905C20.8604 9.20478 20.7526 8.98444 20.608 8.78886C20.4447 8.56806 20.218 8.39175 19.7646 8.03913L12.9823 2.764Z" stroke="white" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/></svg>
                            <div>Dashboard</div>
                        </a></li>
                        <li><a href="{% url 'finance:income' %}">
                            <svg width="20px" height="20px" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M13.5295 8.35186C12.9571 8.75995 12.2566 9 11.5 9C9.567 9 8 7.433 8 5.5C8 3.567 9.567 2 11.5 2C12.753 2 13.8522 2.65842 14.4705 3.64814M6 20.0872H8.61029C8.95063 20.0872 9.28888 20.1277 9.61881 20.2086L12.3769 20.8789C12.9753 21.0247 13.5988 21.0388 14.2035 20.9214L17.253 20.3281C18.0585 20.1712 18.7996 19.7854 19.3803 19.2205L21.5379 17.1217C22.154 16.5234 22.154 15.5524 21.5379 14.9531C20.9832 14.4134 20.1047 14.3527 19.4771 14.8103L16.9626 16.6449C16.6025 16.9081 16.1643 17.0498 15.7137 17.0498H13.2855L14.8311 17.0498C15.7022 17.0498 16.4079 16.3633 16.4079 15.5159V15.2091C16.4079 14.5055 15.9156 13.892 15.2141 13.7219L12.8286 13.1417C12.4404 13.0476 12.0428 13 11.6431 13C10.6783 13 8.93189 13.7988 8.93189 13.7988L6 15.0249M20 6.5C20 8.433 18.433 10 16.5 10C14.567 10 13 8.433 13 6.5C13 4.567 14.567 3 16.5 3C18.433 3 20 4.567 20 6.5ZM2 14.6L2 20.4C2 20.9601 2 21.2401 2.10899 21.454C2.20487 21.6422 2.35785 21.7951 2.54601 21.891C2.75992 22 3.03995 22 3.6 22H4.4C4.96005 22 5.24008 22 5.45399 21.891C5.64215 21.7951 5.79513 21.6422 5.89101 21.454C6 21.2401 6 20.9601 6 20.4V14.6C6 14.0399 6 13.7599 5.89101 13.546C5.79513 13.3578 5.64215 13.2049 5.45399 13.109C5.24008 13 4.96005 13 4.4 13L3.6 13C3.03995 13 2.75992 13 2.54601 13.109C2.35785 13.2049 2.20487 13.3578 2.10899 13.546C2 13.7599 2 14.0399 2 14.6Z" stroke="white" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/></svg>
                            <div>Income</div>
                        </a></li>
                        <li><a href="{% url 'finance:expenses' %}">
                            <svg width="20px" height="20px" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M6 11V15M18 9V13M17 4C19.4487 4 20.7731 4.37476 21.4321 4.66544C21.5199 4.70415 21.5638 4.72351 21.6904 4.84437C21.7663 4.91682 21.9049 5.12939 21.9405 5.22809C22 5.39274 22 5.48274 22 5.66274V16.4111C22 17.3199 22 17.7743 21.8637 18.0079C21.7251 18.2454 21.5914 18.3559 21.3319 18.4472C21.0769 18.5369 20.562 18.438 19.5322 18.2401C18.8114 18.1017 17.9565 18 17 18C14 18 11 20 7 20C4.55129 20 3.22687 19.6252 2.56788 19.3346C2.48012 19.2958 2.43624 19.2765 2.3096 19.1556C2.23369 19.0832 2.09512 18.8706 2.05947 18.7719C2 18.6073 2 18.5173 2 18.3373L2 7.58885C2 6.68009 2 6.2257 2.13628 5.99214C2.2749 5.75456 2.40859 5.64412 2.66806 5.55281C2.92314 5.46305 3.43803 5.56198 4.46783 5.75985C5.18862 5.89834 6.04348 6 7 6C10 6 13 4 17 4ZM14.5 12C14.5 13.3807 13.3807 14.5 12 14.5C10.6193 14.5 9.5 13.3807 9.5 12C9.5 10.6193 10.6193 9.5 12 9.5C13.3807 9.5 14.5 10.6193 14.5 12Z" stroke="white" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/></svg>
                            <div>Expenses</div>
                        </a></li>
                        <li><a href="{% url 'finance:budgets' %}">
                            <svg width="20px" height="20px" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M2 17V16.8498C2 16.5333 2 16.3751 2.02421 16.2209C2.0457 16.084 2.08136 15.9497 2.13061 15.8202C2.18609 15.6743 2.2646 15.5369 2.42162 15.2622L6 9M2 17C2 19.2091 3.79086 21 6 21C8.20914 21 10 19.2091 10 17M2 17V16.8C2 16.52 2 16.38 2.0545 16.273C2.10243 16.1789 2.17892 16.1024 2.273 16.0545C2.37996 16 2.51997 16 2.8 16H9.2C9.48003 16 9.62004 16 9.727 16.0545C9.82108 16.1024 9.89757 16.1789 9.9455 16.273C10 16.38 10 16.52 10 16.8V17M6 9L9.57838 15.2622C9.7354 15.5369 9.81391 15.6743 9.86939 15.8202C9.91864 15.9497 9.9543 16.084 9.97579 16.2209C10 16.3751 10 16.5333 10 16.8498V17M6 9L18 7M14 15V14.8498C14 14.5333 14 14.3751 14.0242 14.2209C14.0457 14.084 14.0814 13.9497 14.1306 13.8202C14.1861 13.6743 14.2646 13.5369 14.4216 13.2622L18 7M14 15C14 17.2091 15.7909 19 18 19C20.2091 19 22 17.2091 22 15M14 15V14.8C14 14.52 14 14.38 14.0545 14.273C14.1024 14.1789 14.1789 14.1024 14.273 14.0545C14.38 14 14.52 14 14.8 14H21.2C21.48 14 21.62 14 21.727 14.0545C21.8211 14.1024 21.8976 14.1789 21.9455 14.273C22 14.38 22 14.52 22 14.8V15M18 7L21.5784 13.2622C21.7354 13.5369 21.8139 13.6743 21.8694 13.8202C21.9186 13.9497 21.9543 14.084 21.9758 14.2209C22 14.3751 22 14.5333 22 14.8498V15M12 3V8" stroke="white" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/></svg>
                            <div>Budgets</div>
                        </a></li>
                        <li><a href="{% url 'finance:reports' %}">
                            <svg width="20px" height="20px" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M14 2.26953V6.40007C14 6.96012 14 7.24015 14.109 7.45406C14.2049 7.64222 14.3578 7.7952 14.546 7.89108C14.7599 8.00007 15.0399 8.00007 15.6 8.00007H19.7305M8 15V18M16 13V18M12 10.5V18M20 9.98822V17.2C20 18.8802 20 19.7202 19.673 20.362C19.3854 20.9265 18.9265 21.3854 18.362 21.673C17.7202 22 16.8802 22 15.2 22H8.8C7.11984 22 6.27976 22 5.63803 21.673C5.07354 21.3854 4.6146 20.9265 4.32698 20.362C4 19.7202 4 18.8802 4 17.2V6.8C4 5.11984 4 4.27976 4.32698 3.63803C4.6146 3.07354 5.07354 2.6146 5.63803 2.32698C6.27976 2 7.11984 2 8.8 2H12.0118C12.7455 2 13.1124 2 13.4577 2.08289C13.7638 2.15638 14.0564 2.27759 14.3249 2.44208C14.6276 2.6276 14.887 2.88703 15.4059 3.40589L18.5941 6.59411C19.113 7.11297 19.3724 7.3724 19.5579 7.67515C19.7224 7.94356 19.8436 8.2362 19.9171 8.5423C20 8.88757 20 9.25445 20 9.98822Z" stroke="white" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/></svg>
                            <div>Reports</div>
                        </a></li>
                    </ul>
                </div>
            </li>
            <a href="{% url 'dashboard:dashboard' %}" class="logo-link">
                {% load static %}
                <img src="{% static 'dashboard/logo.png' %}">
            </a>
            <li>{% block header-title %}Dashboard{% endblock %}</li>
        </ul>
        <ul class="header-right-side">
            {% if request.user.is_authenticated %}
                <p>Logged in as {{ request.user.username }}</p>
                <form method="POST" action="{% url 'authentication:logout' %}">
                    {% csrf_token %}
                    <button type="submit">Log out</a>
                </form>
            {% else %}
                <a href="{% url 'authentication:login' %}">Log in</a>
            {% endif %}
        </ul>
    </div>

    <!-- If any success or error messages need to be displayed, this is done here -->
    {% if messages %}
        <h3>Alert:</h3>
        <ul>
            {% for message in messages %}
                {% if message.tags == "error" %}
                    <li style="color: red">{{ message }}</li>
                {% else %}
                    <li style="color: green">{{ message }}</li>
                {% endif %}
            {% endfor %}
        </ul>
    {% endif %}

    <!-- The main content for all templates that inherit from this one goes here -->
    {% block content %}{% endblock %}
</body>
</html>